export const paths = {
  SPLASH: "Splash",
  LOGIN: "Login",
  SIGNUP: "Signup",
  HOME: "Home",
  BOTTOMNAVIGATION: "BottomNavigation",
  ONBOARDING: "Onboarding",
  HOMESTACK: "HomeStack",
  INSPECT: "Inspect",
  INSPECTSTACK: "InspectStack",
  AUTHSTACK: "AuthStack",
  DETAILS: 'Details',
  INVENTORY: 'Inventory',
  INVENTORYSTACK: 'InventoryStack',
  PROFILE: 'Profile',
  PROFILESTACK: 'ProfileStack',
  SEARCH: 'Search',
  CREATEFARM: 'CreateFarm',
} as const;
